apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.api_id }}-api-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/smongiar/developer-charts
    targetRevision: HEAD
    path: api-specification-pipeline
    helm:
      values: |
        domain: smongiar
        system: ${{values.application.split("/")[1]}}
        component: ${{ values.component_id }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split("/")[1]}}-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m