apiVersion: batch/v1
kind: Job
metadata:
  name: ${{ values.api_id }}-api-pipeline-run-job
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector: {}
  template:
    metadata:
      name: ${{ values.api_id }}-api-pipeline-run-job
    spec:
      containers:
          - name: ${{ values.api_id }}-api-pipeline-run-job
            image: gcr.io/tekton-releases/dogfooding/tkn
            command:
              - /bin/sh
              - -c
              - |
                tkn pipeline start ${{ values.api_id }}-api -w name=shared-data,claimName=${{ values.api_id }}-shared-data -w name=maven-settings,claimName=${{ values.api_id }}-maven-settings --use-param-defaults
            env:
              - name: HOME
                value: /tekton/home
      restartPolicy: Never
      serviceAccountName: pipeline