---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ values.api_id }}-shared-data
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ values.api_id }}-maven-settings
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce