- restConfiguration:
    apiContextPath: /api-doc
    #bindingMode: json
    #bindingPackageScan: ${{ values.java_package }}.model

- rest:
    id: rest-openapi
    openApi:
      id: openapi-configuration
      specification: https://raw.githubusercontent.com/smongiar/${{values.application.split("/")[1]}}-${{ values.api_id }}-api/main/specification.yaml
      missingOperation: ignore